module Orthoses
  class Audited
    interface _Loader
      def call: () -> Store
    end

    VERSION: String

    @loader: _Loader
    @audit_class: String

    def initialize: (_Loader loader, ?audit_class: String) -> void

    def call: () -> Store
  end
end
